Attempt at PlayerCache iterating (Failed)
This is currently bugged as after loading the player's data on join, it complains about their values being null.

Example Stacktrace:
[21:31:30] [Craft Scheduler Thread - 13 - UltraColor/WARN]: [UltraColor] Plugin UltraColor v1.5.9.2 generated an exception while executing task 45
java.lang.NullPointerException: Cannot invoke "String.equalsIgnoreCase(String)" because the return value of "me.ultimategamer200.ultracolor.PlayerCache.getColoredNickName()" is null
	at me.ultimategamer200.ultracolor.util.UltraColorUtil.getPlayerNameInColor(UltraColorUtil.java:495) ~[UltraColor-1.5.9.2.jar:?]
	at me.ultimategamer200.ultracolor.listeners.PlayerListener.lambda$onJoin$1(PlayerListener.java:40) ~[UltraColor-1.5.9.2.jar:?]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-411]
	at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[patched_1.17.1.jar:git-Paper-411]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Paper-411]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
	at java.lang.Thread.run(Thread.java:831) ~[?:?]